#!/bin/sh
set -eu

tool_dir=.tools/bin
mkdir -p "$tool_dir"
install() {
  package=$1
  GOBIN="$(pwd)/$tool_dir" go install "$package"
}

install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.13.2
install golang.org/x/vuln/cmd/govulncheck@v1.7.0
install github.com/google/osv-scanner/v2/cmd/osv-scanner@v2.5.1
install github.com/zricethezav/gitleaks/v8@v8.30.1
install github.com/go-gremlins/gremlins/cmd/gremlins@v0.6.0
